version: '2'

services:

    web:
        build:
            context: .docker/nginx
        volumes:
            - ./:/var/www:cached
        ports:
            - "80:80"
        extra_hosts:
            - "dockerhost:10.0.75.1"

    app:
        build:
            context: .docker/php
            args:
                PUID: "1000"
                # PHP_INSTALL_XDEBUG: "false"
                # INSTALL_GIT: "true"
                # PHP_XDEBUG_PORT: "9000"
        volumes:
            - ./:/var/www:cached
#            - .docker/php/xdebug_custom.ini:/usr/local/etc/php/conf.d/51-xdebug-custom.ini
        environment:
            - "REDIS_HOST=redis"
            - "PHP_IDE_CONFIG=serverName=localhost"
        user: www-data
        extra_hosts:
            - "dockerhost:10.0.75.1"

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=test"
            - "MYSQL_PASSWORD=user"
            - "MYSQL_USER=password"
        ports:
            - "3306:3306"
        volumes:
            - ./:/var/www

    redis:
        image: redis:4.0.2
        ports:
            - "6379:6379"
